spring:
  application:
    name: checkout-service
  config:
    import: 
      - "optional:configserver:http://localhost:9004"
  cloud:
    config:
      discovery:
        serviceId: config-service
        enabled: true  
    
server:
  port: 8085
