spring:
  application:
    name: checkout-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      discovery:
        serviceId: config-service
        enabled: true  
    
server:
  port: 8085
